import type {
  User,
  JobRequisition,
  Applicant,
  DashboardMetrics,
} from './types';

export const MOCK_USERS: User[] = [
  {
    id: 'mgr-001',
    email: 'dal266866@utdallas.edu',
    name: 'Hiring Admin',
    role: 'manager',
    department: 'Human Resources',
    title: 'System Administrator',
    initials: 'HA',
    lastLogin: '2026-05-07T08:42:00Z',
  },
];

export const MOCK_CREDENTIALS: Record<string, string> = {
  'dal266866@utdallas.edu': 'password123',
};

export const MOCK_REQUISITIONS: JobRequisition[] = [
  {
    id: 'req-001',
    code: 'REQ-001',
    title: 'Student IT Support Technician',
    department: 'Office of Information Technology',
    location: 'Richardson, TX',
    remote: false,
    employmentType: 'PART_TIME',
    seniorityLevel: 'ENTRY',
    status: 'OPEN',
    headcount: 3,
    filledCount: 0,
    salary: { min: 12, max: 15, currency: 'USD/hr' },
    hiringManagerId: 'mgr-001',
    hiringManagerName: 'Hiring Admin',
    description:
      'The Office of Information Technology (OIT) at UT Dallas is seeking enthusiastic student workers to provide front-line technical support to students, faculty, and staff. You will assist with account access, software installation, network connectivity, and general troubleshooting at the campus help desk and via remote support channels.',
    requirements: [
      'Currently enrolled as a full-time UT Dallas undergraduate or graduate student',
      'Minimum 2.5 cumulative GPA',
      'Basic understanding of Windows and macOS operating systems',
      'Strong verbal and written communication skills',
      'Ability to work 15–20 hours per week including some weekend shifts',
    ],
    niceToHave: [
      'Prior IT support or customer service experience',
      'CompTIA A+ or equivalent certification',
      'Familiarity with Active Directory and ticketing systems',
    ],
    aiScreeningEnabled: true,
    aiScreeningCriteria:
      'Require active UT Dallas enrollment. Prioritize candidates with prior technical support or help desk experience. Flag any candidates below 2.5 GPA if stated.',
    createdAt: '2026-05-01T09:00:00Z',
    publishedAt: '2026-05-02T08:00:00Z',
    applicationCount: 0,
    activeApplicationCount: 0,
  },
  {
    id: 'req-002',
    code: 'REQ-002',
    title: 'Undergraduate Research Assistant',
    department: 'Erik Jonsson School of Engineering',
    location: 'Richardson, TX',
    remote: false,
    employmentType: 'PART_TIME',
    seniorityLevel: 'ENTRY',
    status: 'OPEN',
    headcount: 2,
    filledCount: 0,
    salary: { min: 13, max: 16, currency: 'USD/hr' },
    hiringManagerId: 'mgr-001',
    hiringManagerName: 'Hiring Admin',
    description:
      'The Erik Jonsson School of Engineering & Computer Science is seeking motivated undergraduate students to assist faculty researchers with ongoing lab projects in areas including machine learning, embedded systems, and software engineering. Students will gain hands-on research experience, contribute to publications, and develop skills directly applicable to graduate school or industry careers.',
    requirements: [
      'Currently enrolled as a UT Dallas undergraduate student (sophomore standing or above)',
      'Minimum 3.0 GPA in major coursework',
      'Completed at least one course in programming (CS 1336 or equivalent)',
      'Ability to commit 10–15 hours per week during the semester',
      'Demonstrated interest in research through coursework or personal projects',
    ],
    niceToHave: [
      'Experience with Python, MATLAB, or C/C++',
      'Prior lab or research experience (high school or community college)',
      'Familiarity with version control (Git)',
    ],
    aiScreeningEnabled: true,
    aiScreeningCriteria:
      'Require UT Dallas undergraduate enrollment and sophomore+ standing. Prioritize STEM majors with strong GPA. Flag candidates with no programming coursework.',
    createdAt: '2026-05-01T09:30:00Z',
    publishedAt: '2026-05-02T08:00:00Z',
    applicationCount: 0,
    activeApplicationCount: 0,
  },
  {
    id: 'req-003',
    code: 'REQ-003',
    title: 'McDermott Library Student Assistant',
    department: 'Eugene McDermott Library',
    location: 'Richardson, TX',
    remote: false,
    employmentType: 'PART_TIME',
    seniorityLevel: 'ENTRY',
    status: 'OPEN',
    headcount: 4,
    filledCount: 0,
    salary: { min: 10, max: 12, currency: 'USD/hr' },
    hiringManagerId: 'mgr-001',
    hiringManagerName: 'Hiring Admin',
    description:
      'The Eugene McDermott Library is hiring student assistants to support daily library operations. Responsibilities include assisting patrons at the service desk, shelving and organizing materials, processing new acquisitions, and supporting library events. This is an excellent opportunity for students interested in information science, research services, or academic administration.',
    requirements: [
      'Currently enrolled as a UT Dallas student (undergraduate or graduate)',
      'Minimum 2.0 cumulative GPA',
      'Ability to stand and walk for extended periods and lift up to 25 lbs',
      'Punctual and dependable with strong attention to detail',
      'Availability for at least two evening shifts per week (until 9 PM)',
    ],
    niceToHave: [
      'Prior customer service or retail experience',
      'Interest in library science or archival studies',
      'Bilingual (Spanish or Mandarin a plus for patron services)',
    ],
    aiScreeningEnabled: false,
    createdAt: '2026-05-02T10:00:00Z',
    publishedAt: '2026-05-03T08:00:00Z',
    applicationCount: 0,
    activeApplicationCount: 0,
  },
  {
    id: 'req-004',
    code: 'REQ-004',
    title: 'Campus Recreation Center Attendant',
    department: 'Student Affairs — Campus Recreation',
    location: 'Richardson, TX',
    remote: false,
    employmentType: 'PART_TIME',
    seniorityLevel: 'ENTRY',
    status: 'OPEN',
    headcount: 5,
    filledCount: 0,
    salary: { min: 10, max: 11, currency: 'USD/hr' },
    hiringManagerId: 'mgr-001',
    hiringManagerName: 'Hiring Admin',
    description:
      'UT Dallas Campus Recreation is looking for friendly, energetic student workers to staff the Recreation Center. Attendants monitor facility usage, assist members with equipment, enforce safety policies, handle equipment check-out, and maintain a welcoming environment. Flexible scheduling is available around class commitments, including early morning, evening, and weekend shifts.',
    requirements: [
      'Currently enrolled as a UT Dallas student',
      'Minimum 2.0 cumulative GPA and satisfactory academic progress',
      'CPR/AED certification (or willingness to obtain within 30 days of hire)',
      'Friendly, professional demeanor and ability to enforce policies calmly',
      'Availability for at least 12 hours per week including one weekend shift',
    ],
    niceToHave: [
      'Prior fitness, recreation, or customer service work experience',
      'Personal Trainer or Group Fitness certification',
      'Experience with point-of-sale or membership management software',
    ],
    aiScreeningEnabled: false,
    createdAt: '2026-05-02T11:00:00Z',
    publishedAt: '2026-05-03T08:00:00Z',
    applicationCount: 0,
    activeApplicationCount: 0,
  },
];

export const MOCK_APPLICANTS: Applicant[] = [];

export const MOCK_DASHBOARD_METRICS: DashboardMetrics = {
  totalOpenRequisitions: 4,
  totalHeadcountNeeded: 14,
  totalActiveApplications: 0,
  totalHiredThisMonth: 0,
  totalHiredThisQuarter: 0,
  avgTimeToFillDays: 0,
  offerAcceptanceRate: 0,
  applicationsByDepartment: [],
  pipelineMetrics: {
    received: 0,
    screening: 0,
    review: 0,
    interview: 0,
    decision: 0,
    hired: 0,
    rejected: 0,
  },
  recentActivity: [],
  timeToHireByDept: [],
};
